[project]
name = "ohsome-api"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HeiGIT gGmbH", email = "ohsome@heigit.org" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ohsome-api = "ohsome_api:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "prek>=0.3.5",
    "pytest>=9.0.2",
    "ruff==0.15.5",
]
