apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ohsome-api.fullname" . }}
  labels:
    {{- include "ohsome-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ohsome-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ohsome-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ohsome-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
