apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ohsome-api.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: kta-internal
  labels:
    {{- include "ohsome-api.labels" . | nindent 4 }}
spec:
  ingressClassName: internal
  rules:
    - host: ohsome-api.heigitk8s.de
      http:
        paths:
        - pathType: ImplementationSpecific
          path: "/"
          backend:
            service:
              name: ohsome-api-integration
              port: 
                number: 80
  tls:
    - hosts:
      - ohsome-api.heigitk8s.de
      secretName: ohsome-api.heigitk8s.de-tls
