apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohsome-api.fullname" . }}
  labels:
    {{- include "ohsome-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ohsome-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
