# Default values for ohsome-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: repo.heigit.org/heigit/ohsome-api
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# envFrom:
#   - secretRef:
#       name: my-secret

extraDeploy: []
