# Configuration for ohsome-api and uvicorn

version: 1
disable_existing_loggers: false

formatters:
  ohsome-api:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(funcName)s -
      %(message)s'
  uvicorn:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  ohsome-api:
    class: logging.StreamHandler
    formatter: ohsome-api
    stream: ext://sys.stdout
  uvicorn:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stderr

loggers:
  ohsome-api:
    level: INFO
    handlers: [ohsome-api]
    propagate: false
  uvicorn:
    handlers: [uvicorn]
    level: INFO
    propagate: false

root:
  level: INFO
  handlers: [ohsome-api]
