version: 1
disable_existing_loggers: false

formatters:
  ohsome-api:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(funcName)s -
      %(message)s'
  uvicorn:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  uvicorn.access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(client_addr)s -
      "%(request_line)s" - %(status_code)s'

handlers:
  ohsome-api:
    class: logging.StreamHandler
    formatter: ohsome-api
    stream: ext://sys.stdout
  uvicorn:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stderr
  uvicorn.access:
    class: logging.StreamHandler
    formatter: uvicorn.access
    stream: ext://sys.stdout

loggers:
  ohsome-api:
    level: INFO
    handlers: [ohsome-api]
    propagate: false
  uvicorn:
    handlers: [uvicorn]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [uvicorn.access]
    level: INFO
    propagate: false

root:
  level: INFO
  handlers: [ohsome-api]
